# Generated by Django 6.0.3 on 2026-04-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=10, unique=True)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "prioritaire",
                    models.BooleanField(
                        default=False, help_text="Ville prioritaire pour le stage"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ville",
                "ordering": ["-prioritaire", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agences",
                        to="core.ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agence",
                "ordering": ["ville__prioritaire", "ville__nom", "nom"],
            },
        ),
    ]
