# Generated by Django 6.0.3 on 2026-04-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_agence DROP COLUMN IF EXISTS ville CASCADE;",
            reverse_sql="ALTER TABLE core_agence ADD COLUMN ville character varying(100) NOT NULL DEFAULT '';",
        ),
    ]
