# Generated by Django 6.0.3 on 2026-04-11 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_analyse", models.DateTimeField(auto_now_add=True)),
                ("nb_clients_total", models.IntegerField(default=0)),
                ("nb_clients_haut_risque", models.IntegerField(default=0)),
                ("nb_clients_moyen_risque", models.IntegerField(default=0)),
                ("nb_clients_faible_risque", models.IntegerField(default=0)),
                ("score_churn_moyen", models.FloatField(default=0.0)),
                ("nb_recommandations_generees", models.IntegerField(default=0)),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("mock", "Données simulées"),
                            ("csv", "Import CSV"),
                            ("api", "API Externe"),
                        ],
                        default="mock",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="core.agence",
                    ),
                ),
                (
                    "lancee_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses_lancees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session d'analyse",
                "verbose_name_plural": "Sessions d'analyse",
                "ordering": ["-date_analyse"],
            },
        ),
    ]
