# Generated by Django 6.0.3 on 2026-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_add_analyse_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="archive",
            field=models.BooleanField(default=False),
        ),
    ]
