# Generated by Django 6.0.3 on 2026-04-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_add_archive_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="date_suppression",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="supprimee",
            field=models.BooleanField(default=False),
        ),
    ]
