# Generated by Django 6.0.3 on 2026-04-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_notification_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysesession",
            name="date_suppression",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysesession",
            name="supprimee",
            field=models.BooleanField(default=False),
        ),
    ]
