# Generated by Django 6.0.3 on 2026-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_analysesession_date_suppression_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommandation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("en_cours", "En cours"),
                    ("completee", "Complétée"),
                    ("retiree", "Rejetée"),
                    ("expiree", "Expirée"),
                ],
                default="active",
                max_length=25,
            ),
        ),
    ]
