# Generated by Django 6.0.3 on 2026-04-20 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_recommandation_statut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recommandation",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recs_creees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recommandation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente_validation", "En attente de validation"),
                    ("active", "Active"),
                    ("en_cours", "En cours"),
                    ("completee", "Complétée"),
                    ("retiree", "Rejetée"),
                    ("expiree", "Expirée"),
                ],
                default="active",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="RejetRecommandation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "explication",
                    models.TextField(
                        help_text="Pourquoi voulez-vous rejeter cette recommandation ?"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("note_validation", models.TextField(blank=True)),
                (
                    "demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejets_demandes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommandation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejets",
                        to="dashboard.recommandation",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejets_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rejet de recommandation",
                "verbose_name_plural": "Rejets de recommandations",
                "ordering": ["-date_demande"],
            },
        ),
    ]
