# Generated by Django 6.0.3 on 2026-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0007_recommandation_cree_par_alter_recommandation_statut_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analysesession",
            name="auc_roc",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysesession",
            name="f1_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysesession",
            name="precision",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysesession",
            name="recall",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysesession",
            name="seuil_optimal",
            field=models.FloatField(default=0.25),
        ),
    ]
