# Generated by Django 6.0.3 on 2026-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_analysesession_auc_roc_analysesession_f1_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysesession",
            name="nb_clients_faible_risque",
        ),
        migrations.RemoveField(
            model_name="analysesession",
            name="nb_clients_haut_risque",
        ),
        migrations.RemoveField(
            model_name="analysesession",
            name="nb_clients_moyen_risque",
        ),
        migrations.AddField(
            model_name="analysesession",
            name="nb_clients_churn",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysesession",
            name="nb_clients_non_churn",
            field=models.IntegerField(default=0),
        ),
    ]
