# Generated by Django 4.2.30 on 2026-05-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_recommandation_statut_completee_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommandation",
            name="clv_estimee",
            field=models.FloatField(
                blank=True,
                help_text="Estimation CLV (DT) au moment de la génération",
                null=True,
            ),
        ),
    ]
