# Generated by Django 6.0.3 on 2026-04-16 23:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrateur"),
                    ("admin", "Administrateur Ville"),
                    ("chef_agence", "Chef d'agence"),
                    ("agent_marketing", "Agent Marketing"),
                    ("agent_commercial", "Agent Commercial"),
                ],
                max_length=20,
            ),
        ),
    ]
