# Generated by Django 6.0.3 on 2026-04-20 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_alter_user_role"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminVille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_nomination", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role__in": ["admin", "super_admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_ville",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administrateurs",
                        to="core.ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrateur de ville",
                "verbose_name_plural": "Administrateurs de ville",
                "permissions": [
                    (
                        "valider_chef_agence",
                        "Peut valider les chefs d'agence de sa ville",
                    ),
                    (
                        "gerer_utilisateurs_ville",
                        "Peut gérer les utilisateurs de sa ville",
                    ),
                ],
            },
        ),
    ]
