# Generated by Django 6.0.3 on 2026-04-20 12:02

from django.db import migrations


def migrate_admins_to_adminville(apps, schema_editor):
    """Transfère les admins existants vers le modèle AdminVille"""
    User = apps.get_model('accounts', 'User')
    AdminVille = apps.get_model('accounts', 'AdminVille')
    
    # Créer AdminVille pour tous les admins/super_admins existants
    for user in User.objects.filter(role__in=['admin', 'super_admin']):
        if user.ville:  # Si l'admin a une ville assignée
            AdminVille.objects.get_or_create(
                user=user,
                defaults={'ville': user.ville, 'actif': True}
            )


def reverse_migrate_admins(apps, schema_editor):
    """Rollback: transfère les données AdminVille vers User.ville"""
    User = apps.get_model('accounts', 'User')
    AdminVille = apps.get_model('accounts', 'AdminVille')
    
    for admin_ville in AdminVille.objects.all():
        user = admin_ville.user
        user.ville = admin_ville.ville
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_adminville_model"),
    ]

    operations = [
        migrations.RunPython(migrate_admins_to_adminville, reverse_migrate_admins),
    ]
