# Generated by Django 6.0.3 on 2026-04-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_migrate_admins_to_adminville"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agence',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employes',
                to='core.agence',
            ),
        ),
    ]
