# Generated by Django 6.0.3 on 2026-04-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_agence_null"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE accounts_user ALTER COLUMN agence_id DROP NOT NULL;",
            reverse_sql="ALTER TABLE accounts_user ALTER COLUMN agence_id SET NOT NULL;",
        ),
    ]
