# Generated by Django 6.0.3 on 2026-04-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type_modele",
                    models.CharField(
                        choices=[
                            ("xgboost", "XGBoost"),
                            ("random_forest", "Random Forest"),
                            ("logistic", "Régression Logistique"),
                            ("neural", "Réseau de neurones"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fichier_pkl", models.FileField(upload_to="models/")),
                ("accuracy", models.FloatField(default=0)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("csv", "Upload CSV"),
                            ("db", "Base de données"),
                            ("api", "API externe"),
                            ("mock", "Données mock"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="datasets/"),
                ),
                ("date_chargement", models.DateTimeField(auto_now_add=True)),
                ("nb_clients", models.IntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agence"
                    ),
                ),
                (
                    "charge_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset",
            },
        ),
        migrations.CreateModel(
            name="ClientChurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=100)),
                ("nom", models.CharField(blank=True, max_length=200)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email", models.CharField(blank=True, max_length=200)),
                ("segment", models.CharField(blank=True, max_length=100)),
                ("anciennete_mois", models.IntegerField(default=0)),
                ("nb_reclamations", models.IntegerField(default=0)),
                ("consommation_moyenne", models.FloatField(default=0)),
                ("retards_paiement", models.IntegerField(default=0)),
                ("nb_services", models.IntegerField(default=0)),
                ("score_churn", models.FloatField(default=0)),
                ("churn_predit", models.BooleanField(default=False)),
                (
                    "niveau_risque",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("moyen", "Moyen"),
                            ("eleve", "Élevé"),
                        ],
                        default="faible",
                        max_length=10,
                    ),
                ),
                ("date_prediction", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agence"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="learning.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Churn",
            },
        ),
    ]
