# Generated by Django 6.0.3 on 2026-04-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientchurn",
            name="recence_cdr_jours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="reclamation_manquante",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="clientchurn",
            name="nb_reclamations",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
