# Generated by Django 6.0.3 on 2026-04-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_clientchurn_recence_cdr_jours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientchurn",
            name="data_mois_M",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="data_mois_M1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="data_totale_mb",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="duree_appel_moyenne_sec",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="duree_appel_totale_sec",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="duree_session_moyenne_sec",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="facture_moyenne_mensuelle",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="moyen_paiement",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="nb_appels",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="nb_evenements_data_cdr",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="nb_sessions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="plan_tarifaire",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="qualite_signal_dominante",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="recence_session_jours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="satisfaction_client",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="score_frustration",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="score_qualite_zone",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="sms_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="taux_cookies",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="tendance_data",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="type_abonnement",
            field=models.CharField(
                choices=[("prepaye", "Prépayé"), ("postpaye", "Post-payé")],
                default="prepaye",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="zone_reseau_principale",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
