# Generated by Django 6.0.3 on 2026-04-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_clientchurn_data_mois_m_clientchurn_data_mois_m1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientchurn",
            name="adresse_physique",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="consentement_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="date_consentement",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="date_debut_abonnement",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="genre_client",
            field=models.CharField(
                blank=True,
                choices=[("Homme", "Homme"), ("Femme", "Femme")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="identifiant_national",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="optout_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="statut_actif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="tenure_jours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="tenure_mois",
            field=models.FloatField(default=0),
        ),
    ]
