# Generated by Django 6.0.3 on 2026-04-19 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_clientchurn_adresse_physique_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvenementCDR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_heure", models.DateTimeField()),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("appel", "Appel"),
                            ("sms", "SMS"),
                            ("donnee_mobile", "Donnée mobile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numero_source", models.CharField(max_length=20)),
                ("numero_destination", models.CharField(max_length=20)),
                ("duree_appel_sec", models.IntegerField(default=0)),
                ("sms_compte", models.IntegerField(default=0)),
                ("data_mb", models.FloatField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements_cdr",
                        to="learning.clientchurn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement CDR",
                "verbose_name_plural": "Événements CDR",
                "ordering": ["-date_heure"],
            },
        ),
    ]
