# Generated by Django 6.0.3 on 2026-04-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_evenementcdr"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampagneMarketing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "type_campagne",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push notification"),
                            ("appel", "Appel sortant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_envoi", models.DateTimeField()),
                ("contenu", models.TextField()),
                ("segment_cible", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Campagne Marketing",
                "verbose_name_plural": "Campagnes Marketing",
            },
        ),
        migrations.CreateModel(
            name="DonneeGeospatiale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=10)),
                ("zone_couverture", models.CharField(blank=True, max_length=100)),
                ("qualite_reseau_local", models.CharField(blank=True, max_length=50)),
                ("signal_dbm", models.IntegerField(blank=True, null=True)),
                ("nb_antennes_proximite", models.IntegerField(default=0)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geolocalisation",
                        to="learning.clientchurn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donnée Géospatiale",
                "verbose_name_plural": "Données Géospatiales",
            },
        ),
        migrations.CreateModel(
            name="InteractionCampagne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reception", models.DateTimeField(blank=True, null=True)),
                ("ouvert", models.BooleanField(default=False)),
                ("date_ouverture", models.DateTimeField(blank=True, null=True)),
                ("clique", models.BooleanField(default=False)),
                ("date_clic", models.DateTimeField(blank=True, null=True)),
                ("converti", models.BooleanField(default=False)),
                ("date_conversion", models.DateTimeField(blank=True, null=True)),
                (
                    "campagne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="learning.campagnemarketing",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagnes",
                        to="learning.clientchurn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction Campagne",
                "verbose_name_plural": "Interactions Campagnes",
            },
        ),
        migrations.CreateModel(
            name="InteractionDigital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_heure", models.DateTimeField()),
                (
                    "type_interaction",
                    models.CharField(
                        choices=[
                            ("connexion_app", "Connexion App"),
                            ("connexion_web", "Connexion Web"),
                            ("recharge", "Recharge en ligne"),
                            ("modif_profil", "Modification profil"),
                            ("consultation_conso", "Consultation conso"),
                            ("activation_option", "Activation option"),
                        ],
                        max_length=50,
                    ),
                ),
                ("duree_session_sec", models.IntegerField(default=0)),
                ("pages_visitees", models.IntegerField(default=0)),
                ("cookies_acceptes", models.BooleanField(default=False)),
                ("action_concluante", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="learning.clientchurn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction Digital",
                "verbose_name_plural": "Interactions Digitales",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.CreateModel(
            name="Reclamation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "type_reclamation",
                    models.CharField(
                        choices=[
                            ("technique", "Technique"),
                            ("facturation", "Facturation"),
                            ("commercial", "Commercial"),
                            ("service", "Service client"),
                            ("couverture", "Couverture réseau"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sujet", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("en_cours", "En cours de traitement"),
                            ("resolu", "Résolu"),
                            ("ferme", "Fermé"),
                        ],
                        default="ouvert",
                        max_length=20,
                    ),
                ),
                ("date_resolution", models.DateTimeField(blank=True, null=True)),
                ("temps_resolution_heures", models.IntegerField(blank=True, null=True)),
                ("satisfait", models.BooleanField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamations",
                        to="learning.clientchurn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réclamation",
                "verbose_name_plural": "Réclamations",
                "ordering": ["-date_creation"],
            },
        ),
    ]
