# Generated by Django 6.0.3 on 2026-04-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_campagnemarketing_donneegeospatiale_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelml",
            options={"verbose_name": "Modèle ML", "verbose_name_plural": "Modèles ML"},
        ),
        migrations.AddField(
            model_name="modelml",
            name="auc",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="modelml",
            name="precision",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="modelml",
            name="recall",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="modelml",
            name="actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="modelml",
            name="fichier_pkl",
            field=models.FileField(blank=True, null=True, upload_to="models/"),
        ),
        migrations.AlterField(
            model_name="modelml",
            name="type_modele",
            field=models.CharField(
                choices=[
                    ("random_forest", "Random Forest"),
                    ("xgboost", "XGBoost"),
                    ("logistic_regression", "Régression Logistique"),
                ],
                max_length=25,
            ),
        ),
    ]
