# Generated by Django 6.0.3 on 2026-04-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning",
            "0007_alter_modelml_options_modelml_auc_modelml_precision_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelml",
            name="actif",
        ),
    ]
