# Generated by Django 6.0.3 on 2026-05-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_remove_modelml_actif"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelML",
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="data_mois_m1_manquante",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="data_mois_m_manquante",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="flag_offre_data",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientchurn",
            name="flag_offre_voix",
            field=models.IntegerField(default=0),
        ),
    ]
