# Generated by Django 6.0.3 on 2026-05-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_add_audit_flags_rgs90"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShapValeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=100)),
                ("valeur", models.FloatField()),
                ("importance", models.FloatField()),
                ("date_calcul", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shap_valeurs",
                        to="learning.clientchurn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur SHAP",
                "verbose_name_plural": "Valeurs SHAP",
                "ordering": ["-importance"],
            },
        ),
    ]
