# Generated by Django 6.0.3 on 2026-05-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0010_add_shap_valeur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientchurn",
            name="niveau_risque",
        ),
    ]
